<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Token>
 */
class TokenFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'customer_name' => fake()->name(),
            'contact_number' => fake()->phoneNumber(),
            'balance_amount' => fake()->randomFloat(2, 100, 5000),
            'status' => fake()->randomElement(['generated', 'used']),
            'token_code' => null, // Will be auto-generated by the model
        ];
    }

    /**
     * Indicate that the token is generated.
     */
    public function generated(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'generated',
        ]);
    }

    /**
     * Indicate that the token is used.
     */
    public function used(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'used',
        ]);
    }
}
